import { useState } from "react";
import { FlatList, Pressable, Text, View, StyleSheet } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
const C = { ink: "#102A2A", teal: "#0F766E", bg: "#F4F8F7", surface: "#FFFFFF", muted: "#64748B", border: "#DCE9E6", coral: "#D9485F", amber: "#D97706" };
const seed = [{ id: "1", title: "Flooding reported near Road X", message: "Response teams are active. Please avoid the area until further notice.", type: "Emergency Alert", date: "Today, 10:20 AM", unread: true }, { id: "2", title: "Water supply maintenance", message: "Water supply may be unavailable from 10 AM–2 PM tomorrow.", type: "Utility Notice", date: "Yesterday, 4:10 PM", unread: true }, { id: "3", title: "Ward clean-up drive", message: "Join the community clean-up drive this Friday at 7 AM.", type: "General Notice", date: "18 Aug 2026", unread: false }];
export default function NotificationsScreen() { const [items, setItems] = useState(seed); return <ScreenContainer containerClassName="bg-[#F4F8F7]" className="px-5"><FlatList data={items} keyExtractor={(x) => x.id} contentContainerStyle={s.content} ListHeaderComponent={<View style={s.header}><Pressable onPress={() => router.back()} style={s.back}><IconSymbol name="arrow.left" size={21} color={C.ink} /></Pressable><View style={{ flex: 1 }}><Text style={s.eyebrow}>YOUR UPDATES</Text><Text style={s.title}>Notifications</Text></View><Pressable onPress={() => setItems(items.map((x) => ({ ...x, unread: false })))}><Text style={s.readAll}>Read all</Text></Pressable></View>} renderItem={({ item }) => <Pressable onPress={() => setItems(items.map((x) => x.id === item.id ? { ...x, unread: false } : x))} style={[s.card, item.unread && s.unread]}><View style={[s.icon, { backgroundColor: item.type === "Emergency Alert" ? "#FCE8EC" : "#FFF1D9" }]}><IconSymbol name={item.type === "Emergency Alert" ? "exclamationmark.triangle.fill" : "bell.fill"} size={19} color={item.type === "Emergency Alert" ? C.coral : C.amber} /></View><View style={{ flex: 1 }}><View style={s.typeRow}><Text style={s.type}>{item.type.toUpperCase()}</Text>{item.unread && <View style={s.dot} />}</View><Text style={s.cardTitle}>{item.title}</Text><Text style={s.message}>{item.message}</Text><Text style={s.date}>{item.date}</Text></View></Pressable>} /></ScreenContainer> }
const s = StyleSheet.create({ content: { paddingTop: 20, paddingBottom: 30 }, header: { flexDirection: "row", alignItems: "center", gap: 13, marginBottom: 25 }, back: { width: 38, height: 38, alignItems: "center", justifyContent: "center" }, eyebrow: { color: C.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, title: { color: C.ink, fontSize: 27, fontWeight: "800", marginTop: 3 }, readAll: { color: C.teal, fontWeight: "800", fontSize: 12 }, card: { backgroundColor: C.surface, borderRadius: 17, padding: 14, marginBottom: 10, flexDirection: "row", gap: 11, borderWidth: 1, borderColor: C.border }, unread: { borderColor: "#B8DDD4", backgroundColor: "#FCFFFE" }, icon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, typeRow: { flexDirection: "row", alignItems: "center", gap: 7 }, type: { color: C.muted, fontSize: 10, fontWeight: "900", letterSpacing: .5 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.coral }, cardTitle: { color: C.ink, fontSize: 14, fontWeight: "800", marginTop: 5 }, message: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 4 }, date: { color: C.muted, fontSize: 10, marginTop: 6 } });
