import { useState } from "react";
import { Alert, Pressable, ScrollView, Text, View, StyleSheet } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
const C = { ink: "#102A2A", teal: "#0F766E", bg: "#F4F8F7", surface: "#FFFFFF", muted: "#64748B", border: "#DCE9E6", coral: "#D9485F" };
const options = ["Fire", "Flood", "Medical", "Accident", "Security"];
export default function SOSScreen() { const [selected, setSelected] = useState(""); const send = () => { if (!selected) return Alert.alert("Choose an emergency type", "Select the closest category so the ward team knows how to respond."); Alert.alert("Are you sure you want to send an SOS?", "Your current location will be shared with the Ward 12 response system.", [{ text: "Cancel", style: "cancel" }, { text: "Send SOS", style: "destructive", onPress: () => Alert.alert("SOS sent", "Ward admin has been notified. For life-threatening emergencies, call 999.", [{ text: "Done", onPress: () => router.back() }]) }]); }; return <ScreenContainer containerClassName="bg-[#F4F8F7]" className="px-5"><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()} style={s.back}><IconSymbol name="arrow.left" size={21} color={C.ink} /><Text style={s.backText}>Back</Text></Pressable><View style={s.hero}><View style={s.heroIcon}><IconSymbol name="exclamationmark.triangle.fill" size={30} color={C.coral} /></View><Text style={s.title}>Send an SOS</Text><Text style={s.subtitle}>Use this for urgent assistance inside Ward 12.</Text></View><Text style={s.label}>What is happening?</Text><View style={s.grid}>{options.map((x) => <Pressable key={x} onPress={() => setSelected(x)} style={[s.option, selected === x && s.optionActive]}><View style={[s.optionIcon, selected === x && { backgroundColor: C.coral }]}><IconSymbol name="exclamationmark.triangle.fill" size={18} color={selected === x ? C.surface : C.coral} /></View><Text style={[s.optionText, selected === x && { color: C.coral }]}>{x}</Text></Pressable>)}</View><View style={s.location}><IconSymbol name="location.fill" size={20} color={C.teal} /><View style={{ flex: 1 }}><Text style={s.locationTitle}>Current location ready</Text><Text style={s.locationText}>Location will be attached automatically.</Text></View><IconSymbol name="checkmark.circle.fill" size={20} color={C.teal} /></View><Pressable onPress={send} style={({ pressed }) => [s.send, pressed && { opacity: .8 }]}><Text style={s.sendText}>Send SOS</Text></Pressable><Text style={s.disclaimer}>WardConnect is a local coordination layer and does not replace Bangladesh’s national emergency number.</Text></ScrollView></ScreenContainer> }
const s = StyleSheet.create({ content: { paddingTop: 17, paddingBottom: 32 }, back: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 24 }, backText: { color: C.ink, fontWeight: "700" }, hero: { alignItems: "center", marginBottom: 29 }, heroIcon: { width: 68, height: 68, borderRadius: 24, backgroundColor: "#FCE8EC", alignItems: "center", justifyContent: "center", marginBottom: 13 }, title: { color: C.ink, fontSize: 29, fontWeight: "800" }, subtitle: { color: C.muted, fontSize: 14, marginTop: 6, textAlign: "center" }, label: { color: C.ink, fontSize: 14, fontWeight: "800", marginBottom: 11 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, option: { width: "47.5%", backgroundColor: C.surface, borderRadius: 16, padding: 14, borderWidth: 1, borderColor: C.border, alignItems: "center", gap: 9 }, optionActive: { borderColor: C.coral, backgroundColor: "#FFF6F7" }, optionIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#FCE8EC", alignItems: "center", justifyContent: "center" }, optionText: { color: C.ink, fontSize: 14, fontWeight: "800" }, location: { marginTop: 20, backgroundColor: C.surface, borderRadius: 15, padding: 14, flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: C.border }, locationTitle: { color: C.ink, fontSize: 13, fontWeight: "800" }, locationText: { color: C.muted, fontSize: 11, marginTop: 3 }, send: { height: 54, backgroundColor: C.coral, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 20 }, sendText: { color: C.surface, fontSize: 16, fontWeight: "900", letterSpacing: .2 }, disclaimer: { color: C.muted, fontSize: 11, textAlign: "center", lineHeight: 17, marginTop: 16 } });
