import { useState } from "react";
import { Alert, Pressable, ScrollView, Text, TextInput, View, StyleSheet } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
const C = { ink: "#102A2A", teal: "#0F766E", bg: "#F4F8F7", surface: "#FFFFFF", muted: "#64748B", border: "#DCE9E6", coral: "#D9485F" };
const categories = ["Road Damage", "Streetlight", "Garbage / Illegal Dumping", "Water Leakage", "Waterlogging", "Power Outage", "Other"];
export default function NewReport() { const [category, setCategory] = useState(""); const [description, setDescription] = useState(""); const [landmark, setLandmark] = useState(""); const submit = () => { if (!category || description.trim().length < 10) return Alert.alert("Add a little more detail", "Choose a category and write at least 10 characters so the ward team can act."); Alert.alert("Report submitted", "Your report has been received by Ward 12.", [{ text: "View my reports", onPress: () => router.replace("/(tabs)/reports") }]); }; return <ScreenContainer containerClassName="bg-[#F4F8F7]" className="px-5"><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => router.back()} style={s.back}><IconSymbol name="arrow.left" size={21} color={C.ink} /><Text style={s.backText}>Back</Text></Pressable><Text style={s.title}>Submit a report</Text><Text style={s.subtitle}>Tell your ward team what needs attention.</Text><Text style={s.label}>Category</Text><View style={s.chips}>{categories.map((x) => <Pressable key={x} onPress={() => setCategory(x)} style={[s.chip, category === x && s.chipActive]}><Text style={[s.chipText, category === x && s.chipTextActive]}>{x}</Text></Pressable>)}</View><Text style={s.label}>What happened?</Text><TextInput multiline value={description} onChangeText={setDescription} placeholder="Describe the issue clearly" placeholderTextColor={C.muted} style={[s.input, s.textarea]} /><Text style={s.label}>Landmark <Text style={s.optional}>(optional)</Text></Text><TextInput value={landmark} onChangeText={setLandmark} placeholder="e.g. Near Kafrul Market" placeholderTextColor={C.muted} style={s.input} /><Text style={s.label}>Photo and location</Text><View style={s.utility}><View style={s.utilityIcon}><IconSymbol name="location.fill" size={19} color={C.teal} /></View><View style={{ flex: 1 }}><Text style={s.utilityTitle}>Location ready to share</Text><Text style={s.utilityText}>Current location will be attached when you submit.</Text></View><IconSymbol name="checkmark.circle.fill" size={20} color={C.teal} /></View><View style={s.utility}><View style={s.utilityIcon}><IconSymbol name="plus.circle.fill" size={19} color={C.teal} /></View><View style={{ flex: 1 }}><Text style={s.utilityTitle}>Add photos</Text><Text style={s.utilityText}>Up to 3 photos · optional</Text></View><Text style={s.add}>Add</Text></View><Pressable onPress={submit} style={({ pressed }) => [s.submit, pressed && { opacity: .8 }]}><Text style={s.submitText}>Submit report</Text><IconSymbol name="chevron.right" size={19} color={C.surface} /></Pressable></ScrollView></ScreenContainer> }
const s = StyleSheet.create({ content: { paddingTop: 17, paddingBottom: 32 }, back: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 23 }, backText: { color: C.ink, fontWeight: "700", fontSize: 14 }, title: { color: C.ink, fontSize: 29, fontWeight: "800" }, subtitle: { color: C.muted, fontSize: 14, marginTop: 6, marginBottom: 25 }, label: { color: C.ink, fontSize: 14, fontWeight: "800", marginBottom: 9, marginTop: 13 }, optional: { color: C.muted, fontWeight: "500" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { borderWidth: 1, borderColor: C.border, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 20, backgroundColor: C.surface }, chipActive: { backgroundColor: "#D6EFEB", borderColor: C.teal }, chipText: { color: C.muted, fontSize: 12, fontWeight: "700" }, chipTextActive: { color: C.teal }, input: { height: 48, borderRadius: 13, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface, paddingHorizontal: 14, color: C.ink, fontSize: 14 }, textarea: { height: 105, paddingTop: 13, textAlignVertical: "top" }, utility: { backgroundColor: C.surface, borderRadius: 15, padding: 13, flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: C.border, marginBottom: 9 }, utilityIcon: { width: 36, height: 36, borderRadius: 11, backgroundColor: "#E3F1EC", alignItems: "center", justifyContent: "center" }, utilityTitle: { color: C.ink, fontSize: 13, fontWeight: "800" }, utilityText: { color: C.muted, fontSize: 11, marginTop: 3 }, add: { color: C.teal, fontSize: 12, fontWeight: "800" }, submit: { backgroundColor: C.teal, height: 53, borderRadius: 16, marginTop: 21, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, submitText: { color: C.surface, fontSize: 15, fontWeight: "800" } });
