import { useMemo, useState } from "react";
import { FlatList, Pressable, Text, TextInput, View, StyleSheet } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { incidents, resources } from "@/lib/ward-data";
const C = { ink: "#102A2A", teal: "#0F766E", bg: "#F4F8F7", surface: "#FFFFFF", muted: "#64748B", border: "#DCE9E6", coral: "#D9485F", amber: "#D97706" };
export default function MapScreen() {
  const [mode, setMode] = useState<"incidents" | "resources">("incidents");
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => resources.filter((r) => `${r.name} ${r.category}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const data: any[] = mode === "incidents" ? incidents : filtered;
  return <ScreenContainer containerClassName="bg-[#F4F8F7]" className="px-5"><FlatList data={data} keyExtractor={(item: any) => mode === "incidents" ? item.id : item.name} contentContainerStyle={s.content} ListHeaderComponent={<MapHeader mode={mode} setMode={setMode} search={search} setSearch={setSearch} />} renderItem={({ item }: any) => mode === "incidents" ? <IncidentRow item={item} /> : <ResourceRow item={item} />} /></ScreenContainer>;
}
function MapHeader({ mode, setMode, search, setSearch }: { mode: "incidents" | "resources"; setMode: (m: "incidents" | "resources") => void; search: string; setSearch: (v: string) => void }) {
  return <View><Text style={s.eyebrow}>WARD AWARENESS</Text><Text style={s.title}>{mode === "incidents" ? "Incident map" : "Resources"}</Text><Text style={s.subtitle}>{mode === "incidents" ? "Verified public updates for Ward 12." : "Find local support services and response contacts."}</Text><View style={s.switcher}><Pressable onPress={() => setMode("incidents")} style={[s.switchItem, mode === "incidents" && s.switchActive]}><Text style={[s.switchText, mode === "incidents" && s.switchTextActive]}>Incidents</Text></Pressable><Pressable onPress={() => setMode("resources")} style={[s.switchItem, mode === "resources" && s.switchActive]}><Text style={[s.switchText, mode === "resources" && s.switchTextActive]}>Resources</Text></Pressable></View>{mode === "incidents" ? <><View style={s.map}><View style={s.roadA} /><View style={s.roadB} /><Marker left="25%" top="35%" color={C.coral} value="1" /><Marker left="62%" top="52%" color={C.amber} value="2" /><Marker left="48%" top="23%" color={C.teal} value="3" /><View style={s.mapLabel}><IconSymbol name="location.fill" size={13} color={C.teal} /><Text style={s.mapLabelText}>Ward 12 · Mirpur</Text></View></View><View style={s.legend}><Text style={s.legendTitle}>Verified incidents only</Text><Text style={s.legendText}>Emergency · Utility · Road works</Text></View><Text style={s.section}>Nearby incidents</Text></> : <View style={s.searchBox}><IconSymbol name="magnifyingglass" size={18} color={C.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search resources" placeholderTextColor={C.muted} style={s.input} /></View>}</View>;
}
function Marker({ left, top, color, value }: { left: any; top: any; color: string; value: string }) { return <View style={[s.marker, { left, top, backgroundColor: color }]}><Text style={s.markerText}>{value}</Text></View>; }
function IncidentRow({ item }: { item: (typeof incidents)[number] }) { return <Pressable onPress={() => router.push((`/incident/${item.id}`) as any)} style={({ pressed }) => [s.row, pressed && { opacity: .75 }]}><View style={[s.dot, { backgroundColor: item.accent }]} /><View style={{ flex: 1 }}><Text style={s.cat}>{item.category.toUpperCase()} · {item.severity}</Text><Text style={s.rowTitle}>{item.title}</Text><Text style={s.meta}>{item.location} · {item.status}</Text></View><IconSymbol name="chevron.right" size={18} color={C.muted} /></Pressable>; }
function ResourceRow({ item }: { item: any }) { return <View style={s.row}><View style={s.resourceIcon}><IconSymbol name="shield.fill" size={19} color={C.teal} /></View><View style={{ flex: 1 }}><Text style={s.rowTitle}>{item.name}</Text><Text style={s.meta}>{item.category} · {item.location}</Text><Text style={s.contact}>{item.contact}</Text></View><IconSymbol name="chevron.right" size={18} color={C.muted} /></View>; }
const s = StyleSheet.create({ content: { paddingTop: 23, paddingBottom: 30 }, eyebrow: { color: C.muted, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { color: C.ink, fontSize: 30, fontWeight: "800", marginTop: 5 }, subtitle: { color: C.muted, fontSize: 14, marginTop: 6 }, switcher: { flexDirection: "row", backgroundColor: "#E6F0EE", borderRadius: 12, padding: 3, marginTop: 18, marginBottom: 15 }, switchItem: { flex: 1, paddingVertical: 10, alignItems: "center", borderRadius: 10 }, switchActive: { backgroundColor: C.surface }, switchText: { color: C.muted, fontWeight: "700", fontSize: 13 }, switchTextActive: { color: C.ink }, map: { height: 210, borderRadius: 19, overflow: "hidden", backgroundColor: "#DDEAE4", position: "relative", borderWidth: 1, borderColor: C.border }, roadA: { position: "absolute", width: 360, height: 16, backgroundColor: "#F7FBF9", transform: [{ rotate: "27deg" }], top: 77, left: -30 }, roadB: { position: "absolute", width: 310, height: 12, backgroundColor: "#F7FBF9", transform: [{ rotate: "-37deg" }], top: 105, left: 40 }, marker: { position: "absolute", width: 29, height: 29, borderRadius: 15, alignItems: "center", justifyContent: "center", borderWidth: 3, borderColor: C.surface }, markerText: { color: C.surface, fontWeight: "900", fontSize: 12 }, mapLabel: { position: "absolute", bottom: 12, left: 12, backgroundColor: C.surface, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7, flexDirection: "row", gap: 5, alignItems: "center" }, mapLabelText: { color: C.ink, fontSize: 11, fontWeight: "800" }, legend: { backgroundColor: C.surface, borderRadius: 14, padding: 12, marginTop: 10, marginBottom: 13 }, legendTitle: { color: C.ink, fontSize: 12, fontWeight: "800" }, legendText: { color: C.muted, fontSize: 11, marginTop: 3 }, section: { color: C.ink, fontSize: 17, fontWeight: "800", marginBottom: 10 }, row: { backgroundColor: C.surface, borderRadius: 15, padding: 14, marginBottom: 9, flexDirection: "row", alignItems: "center", gap: 11, borderWidth: 1, borderColor: C.border }, dot: { width: 10, height: 10, borderRadius: 5 }, cat: { color: C.muted, fontSize: 10, fontWeight: "900", letterSpacing: .5 }, rowTitle: { color: C.ink, fontWeight: "800", fontSize: 14, marginTop: 4 }, meta: { color: C.muted, fontSize: 11, marginTop: 3 }, contact: { color: C.teal, fontSize: 12, fontWeight: "700", marginTop: 5 }, searchBox: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: C.surface, borderRadius: 14, paddingHorizontal: 13, height: 46, borderWidth: 1, borderColor: C.border, marginBottom: 15 }, input: { flex: 1, color: C.ink, fontSize: 14 }, resourceIcon: { height: 38, width: 38, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#E3F1EC" } });
