import { FlatList, Pressable, Text, View, StyleSheet } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { reports, statusLabel } from "@/lib/ward-data";

const C = { ink: "#102A2A", teal: "#0F766E", bg: "#F4F8F7", surface: "#FFFFFF", muted: "#64748B", border: "#DCE9E6", green: "#2F855A", amber: "#D97706" };
export default function ReportsScreen() { return <ScreenContainer containerClassName="bg-[#F4F8F7]" className="px-5"><FlatList data={reports} keyExtractor={(item) => item.id} contentContainerStyle={s.content} ListHeaderComponent={<View><Text style={s.eyebrow}>YOUR ACTIVITY</Text><Text style={s.title}>My reports</Text><Text style={s.subtitle}>Track issues you’ve raised in {"Ward 12"}.</Text><Pressable onPress={() => router.push("/report/new")} style={s.newButton}><IconSymbol name="plus.circle.fill" size={19} color={C.surface} /><Text style={s.newText}>New report</Text></Pressable><Text style={s.section}>Recent submissions</Text></View>} renderItem={({ item }) => <Pressable onPress={() => router.push(`/report/${item.id}`)} style={({ pressed }) => [s.card, pressed && { opacity: 0.75 }]}><View style={s.cardTop}><Text style={s.id}>{item.id}</Text><View style={[s.pill, { backgroundColor: item.status === "in_progress" ? "#FFF1D9" : "#E2F2EA" }]}><Text style={[s.pillText, { color: item.status === "in_progress" ? C.amber : C.green }]}>{statusLabel[item.status]}</Text></View></View><Text style={s.category}>{item.category}</Text><Text style={s.desc} numberOfLines={2}>{item.description}</Text><View style={s.meta}><Text style={s.date}>{item.date}</Text><IconSymbol name="chevron.right" size={18} color={C.muted} /></View></Pressable>} ListEmptyComponent={<Text style={s.empty}>No reports yet.</Text>} /></ScreenContainer> }
const s = StyleSheet.create({ content: { paddingTop: 24, paddingBottom: 30 }, eyebrow: { color: C.muted, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { color: C.ink, fontSize: 30, fontWeight: "800", marginTop: 5 }, subtitle: { color: C.muted, fontSize: 14, marginTop: 6 }, newButton: { backgroundColor: C.teal, borderRadius: 14, height: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 19, marginBottom: 24 }, newText: { color: C.surface, fontSize: 15, fontWeight: "800" }, section: { color: C.ink, fontSize: 17, fontWeight: "800", marginBottom: 11 }, card: { backgroundColor: C.surface, borderRadius: 17, padding: 15, marginBottom: 10, borderWidth: 1, borderColor: C.border }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, id: { color: C.muted, fontSize: 11, fontWeight: "800", letterSpacing: 0.3 }, pill: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 10 }, pillText: { fontSize: 11, fontWeight: "800" }, category: { color: C.ink, fontSize: 16, fontWeight: "800", marginTop: 12 }, desc: { color: C.muted, fontSize: 13, lineHeight: 19, marginTop: 4 }, meta: { borderTopWidth: 1, borderTopColor: C.border, marginTop: 13, paddingTop: 11, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, date: { color: C.muted, fontSize: 11 }, empty: { color: C.muted, marginTop: 30, textAlign: "center" } });
