import { useEffect, useRef } from 'react';
import { LEAFLET_CSS, LEAFLET_JS } from '../vendor/leaflet-assets';

// Click the map or drag the red pin to set a location, like the resident
// app's pin picker. Leaflet is embedded (src/vendor, generated by
// scripts/vendor-leaflet.mjs) and installed on window once.

const DHAKA: [number, number] = [23.8103, 90.4125];
const MAPTILER_KEY = import.meta.env.EXPO_PUBLIC_MAPTILER_KEY || '';
// Same tiles as the app: MapTiler's English-labelled "openstreetmap" style
// (its default style renders Bangla labels broken). Keyless OSM blocks apps.
const TILE_URL = MAPTILER_KEY
  ? `https://api.maptiler.com/maps/openstreetmap/256/{z}/{x}/{y}{r}.png?key=${MAPTILER_KEY}`
  : 'https://tile.openstreetmap.org/{z}/{x}/{y}.png';
const ATTRIBUTION = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' +
  (MAPTILER_KEY ? ' &copy; <a href="https://www.maptiler.com/copyright/">MapTiler</a>' : '');

const PIN_SVG = '<svg width="30" height="42" viewBox="0 0 30 42"><path d="M15 1C7.3 1 1 7.2 1 14.9 1 25.3 15 41 15 41s14-15.7 14-26.1C29 7.2 22.7 1 15 1z" fill="#EA4335" stroke="#B31412" stroke-width="1.5"/><circle cx="15" cy="15" r="5.2" fill="#7A0E0E"/></svg>';

function getLeaflet(): any {
  const w = window as any;
  if (!w.L) {
    const style = document.createElement('style');
    style.textContent = LEAFLET_CSS;
    document.head.appendChild(style);
    // Leaflet's UMD build attaches itself to window.L
    new Function(LEAFLET_JS).call(window);
  }
  return w.L;
}

function parse(lat: string, lng: string): [number, number] | null {
  const a = Number(lat);
  const b = Number(lng);
  return lat.trim() !== '' && lng.trim() !== '' && Number.isFinite(a) && Number.isFinite(b) && Math.abs(a) <= 90 && Math.abs(b) <= 180
    ? [a, b]
    : null;
}

export default function MapPicker({ latitude, longitude, onChange, height = 260 }: {
  latitude: string;
  longitude: string;
  onChange: (latitude: string, longitude: string) => void;
  height?: number;
}) {
  const box = useRef<HTMLDivElement>(null);
  const map = useRef<any>(null);
  const pin = useRef<any>(null);
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;

  // Create the map once
  useEffect(() => {
    const L = getLeaflet();
    const start = parse(latitude, longitude);
    const m = L.map(box.current, { zoomControl: true }).setView(start ?? DHAKA, start ? 16 : 13);
    L.tileLayer(TILE_URL, { maxZoom: 19, attribution: ATTRIBUTION, detectRetina: !MAPTILER_KEY }).addTo(m);
    const icon = L.divIcon({ className: '', html: PIN_SVG, iconSize: [30, 42], iconAnchor: [15, 41] });

    const place = (ll: [number, number], emit: boolean) => {
      if (!pin.current) {
        pin.current = L.marker(ll, { draggable: true, icon }).addTo(m);
        pin.current.on('dragend', () => {
          const p = pin.current.getLatLng();
          onChangeRef.current(p.lat.toFixed(6), p.lng.toFixed(6));
        });
      } else {
        pin.current.setLatLng(ll);
      }
      if (emit) onChangeRef.current(ll[0].toFixed(6), ll[1].toFixed(6));
    };
    if (start) place(start, false);
    m.on('click', (e: any) => place([e.latlng.lat, e.latlng.lng], true));
    map.current = { m, place };
    // The form may have just been revealed; let Leaflet measure its box
    setTimeout(() => m.invalidateSize(), 0);
    return () => {
      m.remove();
      map.current = null;
      pin.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Follow typed coordinates / "Use my location"
  useEffect(() => {
    const ll = parse(latitude, longitude);
    if (!map.current) return;
    if (ll) {
      const cur = pin.current?.getLatLng();
      if (!cur || Math.abs(cur.lat - ll[0]) > 1e-6 || Math.abs(cur.lng - ll[1]) > 1e-6) {
        map.current.place(ll, false);
        map.current.m.setView(ll, Math.max(map.current.m.getZoom(), 16));
      }
    } else if (pin.current) {
      // Both fields cleared: remove the pin
      map.current.m.removeLayer(pin.current);
      pin.current = null;
    }
  }, [latitude, longitude]);

  return (
    <div>
      <div ref={box} style={{ height, borderRadius: '10px', overflow: 'hidden', border: '1px solid var(--border-strong)' }} />
      <p style={{ fontSize: '12px', color: 'var(--muted)', margin: '6px 0 0' }}>
        Click the map to drop the pin, or drag it to adjust. The coordinates above update automatically.
      </p>
    </div>
  );
}
