#!/usr/bin/env node
/**
 * Writes lib/vendor/leaflet-assets.ts: Leaflet's JS and CSS as string
 * constants, so the map page (lib/leaflet-html.ts) embeds them instead of
 * downloading them from a CDN every time a map opens. That download made maps
 * slow to appear, or stay blank on a weak connection.
 *
 * Usage (only needed to change the Leaflet version):  node scripts/vendor-leaflet.mjs
 */
import fs from "fs";
import path from "path";

const VERSION = "1.9.4";
const BASE = `https://cdnjs.cloudflare.com/ajax/libs/leaflet/${VERSION}`;

async function get(file) {
  const res = await fetch(`${BASE}/${file}`);
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  return res.text();
}

const js = await get("leaflet.js");
const css = await get("leaflet.css");
// Both are inlined into <script>/<style> tags, which these would end early.
if (/<\/script/i.test(js) || /<\/style/i.test(css)) throw new Error("Leaflet contains a closing tag; can't inline it");

// One copy for the app, one for the admin dashboard (a separate Vite project
// that can't import from the app's lib/).
for (const rel of ["../lib/vendor/leaflet-assets.ts", "../admin/src/vendor/leaflet-assets.ts"]) {
  const out = path.resolve(import.meta.dirname, rel);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(
    out,
    `// Generated by scripts/vendor-leaflet.mjs from Leaflet ${VERSION} (BSD-2-Clause). Do not edit.\n` +
      `export const LEAFLET_VERSION = ${JSON.stringify(VERSION)};\n` +
      `export const LEAFLET_JS = ${JSON.stringify(js)};\n` +
      `export const LEAFLET_CSS = ${JSON.stringify(css)};\n`,
  );
  console.log(`Wrote ${path.relative(process.cwd(), out)} (${Math.round((js.length + css.length) / 1024)} KB)`);
}
